import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Visualization Recommendations',
  description: 'Explore intelligent, high-confidence chart recommendations generated by Groq-powered AI based on your data distribution and statistical profile.',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
