import type { Metadata } from 'next';
import Link from 'next/link';
import { FileText, ArrowLeft, CheckCircle2, ShieldAlert } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of service and acceptable usage policies for the VizPilot Data Intelligence platform.',
};

export default function TermsPage() {
  return (
    <div className="relative min-h-screen bg-[#08080b] text-white pt-28 sm:pt-36 pb-20 px-4 sm:px-6 md:px-8 lg:px-12">
      <div className="max-w-4xl mx-auto space-y-12">
        {/* Back Link */}
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-xs font-mono text-white/50 hover:text-white transition-colors"
        >
          <ArrowLeft className="h-3.5 w-3.5" />
          <span>BACK TO HOME</span>
        </Link>

        {/* Header */}
        <div className="space-y-4">
          <div className="inline-flex items-center gap-2 rounded-full border border-indigo-400/30 bg-indigo-500/10 px-3.5 py-1 text-xs font-mono font-semibold tracking-wider text-indigo-400 uppercase">
            <FileText className="h-3.5 w-3.5" />
            <span>OPERATIONAL TERMS</span>
          </div>
          <h1 className="font-display text-3xl sm:text-4xl md:text-5xl font-extrabold tracking-tight text-white uppercase">
            Terms of Service
          </h1>
          <p className="text-xs sm:text-sm font-mono text-white/50">
            EFFECTIVE DATE: SEPTEMBER 2026 ï¿½ VIZPILOT PLATFORM AGREEMENT
          </p>
        </div>

        {/* Core Principles */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-5 space-y-2">
            <CheckCircle2 className="h-5 w-5 text-emerald-400" />
            <h2 className="font-display text-base font-bold text-white">Your Data Is Yours</h2>
            <p className="text-xs text-white/60 font-mono leading-relaxed">
              You retain complete ownership, intellectual property, and copyright over all datasets uploaded to VizPilot.
            </p>
          </div>
          <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-5 space-y-2">
            <ShieldAlert className="h-5 w-5 text-indigo-400" />
            <h2 className="font-display text-base font-bold text-white">Acceptable Use</h2>
            <p className="text-xs text-white/60 font-mono leading-relaxed">
              You agree not to upload malware, illicit files, or intentionally tamper with our edge visualization cluster.
            </p>
          </div>
        </div>

        {/* Body sections */}
        <div className="space-y-8 text-sm text-white/70 leading-relaxed font-sans border-t border-white/10 pt-8">
          <section className="space-y-3">
            <h2 className="font-display text-lg font-bold text-white uppercase tracking-wide">
              1. Agreement to Terms
            </h2>
            <p>
              By accessing VizPilot, creating an account, or uploading documents, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-lg font-bold text-white uppercase tracking-wide">
              2. License & Service Provision
            </h2>
            <p>
              VizPilot grants you a limited, non-exclusive, revocable license to access our automated chart generation engine, visual profiling tools, and export facilities. You may freely use charts generated by VizPilot in commercial presentations, corporate reporting, and public dashboards.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-lg font-bold text-white uppercase tracking-wide">
              3. Service Level & Warranty Disclaimer
            </h2>
            <p>
              The service is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. While VizPilot strives for continuous 99.9% uptime and accurate statistical inference, we make no express warranties regarding error-free parsing of non-standard file encodings.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-lg font-bold text-white uppercase tracking-wide">
              4. Contact
            </h2>
            <p>
              For legal inquiries, contract inquiries, or terms clarification, contact our legal counsel at{' '}
              <a
                href="mailto:legal@vizpilot.ai?subject=VizPilot%20Terms%20Inquiry"
                className="text-indigo-400 hover:text-indigo-300 font-mono underline underline-offset-2"
              >
                legal@vizpilot.ai
              </a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
